import { usePage } from '@inertiajs/react';

import StaffLayout from '../../Layouts/StaffLayout';

export default function Dashboard({ dashboard }) {
    const { staff, routes } = usePage().props.staffPortal;
    const cards = [
        ['Total book titles', dashboard.summary.totalTitles, 'Unique books in catalog', routes.books],
        ['Total physical copies', dashboard.summary.totalCopies, 'Physical items in the library', routes.books],
        ['Active members', dashboard.summary.activeMembers, 'Users with active accounts', routes.users],
        ['Currently borrowed', dashboard.summary.borrowedItems, 'Items checked out right now', routes.borrows],
    ];

    return <StaffLayout title="Dashboard" active="dashboard"><div className="mx-auto w-full max-w-[1600px] space-y-5"><section className="grid gap-5 lg:grid-cols-3"><div className="relative flex min-h-[220px] flex-col justify-between overflow-hidden rounded-2xl bg-[#102b70] p-6 text-white shadow-md lg:col-span-2 md:p-8"><div className="absolute -right-10 -top-10 h-64 w-64 rounded-full bg-white/5 blur-3xl" /><div className="relative z-10"><p className="text-xs font-bold uppercase tracking-wider text-white/60">{dashboard.dateLabel}</p><h1 className="mt-4 text-3xl font-black md:text-4xl">Good {dashboard.greeting}, <span className="text-[#fcc719]">{staff.firstName}</span></h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-300">Here is an overview of the library today. Process returns or check out new books from the circulation desk.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href={routes.circulation} className="rounded-xl bg-emerald-500 px-6 py-3 text-center text-sm font-bold text-white">Quick check-in</a><a href={routes.circulation} className="rounded-xl bg-[#fcc719] px-6 py-3 text-center text-sm font-bold text-[#102b70]">Quick check-out</a></div></div></div><Attention dashboard={dashboard} routes={routes} /></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title, value, description, href]) => { const content = <><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1.5 text-2xl font-black text-slate-900">{Number(value).toLocaleString()}</p><p className="mt-2 text-xs font-medium text-slate-400">{description}</p></>; return href ? <a key={title} href={href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:shadow-md">{content}</a> : <div key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{content}</div>; })}</section><section className="grid gap-5 lg:grid-cols-3"><CurrentBorrowers borrowers={dashboard.currentBorrowers} href={routes.borrows} /><MostBorrowed items={dashboard.mostBorrowedItems} /></section></div></StaffLayout>;
}

function Attention({ dashboard, routes }) { return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">Requires attention</h2><div className="mt-4 space-y-4"><a href={routes.borrows} className="flex items-center justify-between rounded-xl border border-red-100 bg-red-50 p-4"><span className="text-sm font-bold text-red-700">Overdue items</span><strong className="text-2xl text-red-700">{dashboard.summary.overdueItems}</strong></a><a href={routes.reservations} className="flex items-center justify-between rounded-xl border border-amber-100 bg-amber-50 p-4"><span className="text-sm font-bold text-amber-700">Pending reservations</span><strong className="text-2xl text-amber-700">{dashboard.summary.pendingReservations}</strong></a></div></div>; }
function CurrentBorrowers({ borrowers, href }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-extrabold text-slate-900">Current borrowers</h2><p className="text-xs text-slate-500">Tracking students and borrow dates</p></div><a href={href} className="rounded-lg bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">View all records</a></div>{borrowers.length ? <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[40rem] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3.5">Student</th><th className="px-5 py-3.5">Book</th><th className="px-5 py-3.5">Borrowed</th><th className="px-5 py-3.5 text-right">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{borrowers.map((borrower, index) => <tr key={`${borrower.memberName}-${borrower.bookTitle}-${index}`}><td className="px-5 py-4 font-bold text-slate-900">{borrower.memberName}</td><td className="px-5 py-4 font-medium text-slate-700">{borrower.bookTitle}</td><td className="px-5 py-4 text-xs text-slate-500">{borrower.borrowDate}</td><td className="px-5 py-4 text-right"><span className={`rounded-md border px-2.5 py-1 text-xs font-bold ${borrower.status.toLowerCase() === 'overdue' ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{borrower.status}</span></td></tr>)}</tbody></table></div> : <Empty message="No current borrowers found." />}</div>; }
function MostBorrowed({ items }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">Most borrowed items</h2><p className="text-xs text-slate-500">Frequently borrowed titles</p>{items.length ? <div className="mt-4 space-y-2">{items.map((item) => <div key={item.bookTitle} className="rounded-xl border border-transparent p-3 hover:border-slate-100 hover:bg-slate-50"><div className="flex items-start justify-between gap-2"><p className="line-clamp-1 text-sm font-bold text-slate-900">{item.bookTitle}</p><span className="whitespace-nowrap rounded-md border border-blue-200 bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700">{item.borrowCount} borrows</span></div><p className="mt-1.5 text-xs text-slate-500">{item.copiesAvailable} available · {item.copiesTotal} total</p></div>)}</div> : <Empty message="No items borrowed yet." />}</div>; }
function Empty({ message }) { return <div className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50 px-4 py-8 text-center text-sm font-semibold text-slate-500">{message}</div>; }
