import { usePage } from '@inertiajs/react';

import StudentLayout from '../../../Layouts/StudentLayout';
import ReservationStatus, { BookCover } from '../../../components/student/ReservationStatus';

export default function Index({ reservations }) {
    const { flash, studentPortal } = usePage().props;

    return <StudentLayout title="Reservations" active="reservations"><div className="mx-auto w-full max-w-[1500px] space-y-5"><section className="flex flex-col gap-4 rounded-2xl bg-[#102b70] p-6 text-white shadow-md sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-200">My Library</p><h1 className="mt-2 text-3xl font-black">My reservations</h1><p className="mt-2 text-sm text-slate-300">Manage your book requests and track their status.</p></div><a href={studentPortal.routes.catalog} className="rounded-xl bg-[#fcc719] px-5 py-3 text-center text-sm font-bold text-[#102b70]">Search catalog</a></section><Flash flash={flash} /><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 bg-slate-50/60 px-5 py-4"><h2 className="font-extrabold text-slate-800">{reservations.meta.total ? `Showing ${reservations.meta.from}–${reservations.meta.to} of ${reservations.meta.total}` : 'No reservations'}</h2></div>{reservations.data.length ? <div className="overflow-x-auto"><table className="w-full min-w-[48rem] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3.5">Book details</th><th className="px-6 py-3.5">Request date</th><th className="px-6 py-3.5 text-center">Status</th><th className="px-6 py-3.5 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{reservations.data.map((reservation) => <tr key={reservation.id} className="hover:bg-slate-50/70"><td className="px-6 py-4"><div className="flex items-center gap-4"><BookCover book={reservation.book} className="h-14 w-10" /><div><p className="font-extrabold text-slate-900">{reservation.book.title}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{reservation.book.authors.length ? reservation.book.authors.join(', ') : 'Unknown author'}</p></div></div></td><td className="px-6 py-4 text-slate-600">{reservation.requestDate || '—'}</td><td className="px-6 py-4 text-center"><ReservationStatus status={reservation.status} statusKey={reservation.statusKey} /></td><td className="px-6 py-4 text-right"><a href={reservation.showUrl} className="rounded-lg bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">View</a></td></tr>)}</tbody></table></div> : <Empty catalogUrl={studentPortal.routes.catalog} />}<Pagination reservations={reservations} /></section></div></StudentLayout>;
}

function Flash({ flash }) { return <>{flash?.success && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{flash.success}</div>}{flash?.error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{flash.error}</div>}</>; }
function Empty({ catalogUrl }) { return <div className="px-6 py-14 text-center"><div className="text-5xl" aria-hidden="true">🗓️</div><h2 className="mt-4 text-lg font-extrabold text-slate-900">No reservations found</h2><p className="mt-2 text-sm text-slate-500">You have not requested any books yet.</p><a href={catalogUrl} className="mt-5 inline-block rounded-xl bg-[#102b70] px-5 py-3 text-sm font-bold text-white">Search catalog</a></div>; }
function Pagination({ reservations }) { if (reservations.meta.lastPage <= 1) return null; return <nav className="flex items-center justify-between border-t border-slate-100 bg-slate-50/50 p-4" aria-label="Reservation pagination"><a href={reservations.links.previous || undefined} className={`rounded-lg px-4 py-2 text-sm font-bold ${reservations.links.previous ? 'text-slate-700 hover:bg-white' : 'pointer-events-none text-slate-300'}`}>Previous</a><span className="text-xs font-semibold text-slate-500">Page {reservations.meta.currentPage} of {reservations.meta.lastPage}</span><a href={reservations.links.next || undefined} className={`rounded-lg px-4 py-2 text-sm font-bold ${reservations.links.next ? 'text-slate-700 hover:bg-white' : 'pointer-events-none text-slate-300'}`}>Next</a></nav>; }
