import { router, usePage } from '@inertiajs/react';
import { useState } from 'react';

import StudentLayout from '../../../Layouts/StudentLayout';
import ReservationStatus, { BookCover } from '../../../components/student/ReservationStatus';

export default function Show({ reservation }) {
    const { flash, studentPortal } = usePage().props;
    const [cancelling, setCancelling] = useState(false);
    const cancel = () => {
        if (!window.confirm('Are you sure you want to cancel this reservation?')) return;
        setCancelling(true);
        router.patch(reservation.cancelUrl, {}, { preserveScroll: true, onFinish: () => setCancelling(false) });
    };

    return <StudentLayout title="Reservation Details" active="reservations"><div className="mx-auto max-w-3xl space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><a href={studentPortal.routes.reservations} className="text-sm font-bold text-slate-500 hover:text-[#102b70]">← Back to reservations</a><ReservationStatus status={reservation.status} statusKey={reservation.statusKey} /></div>{flash?.success && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{flash.success}</div>}{flash?.error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{flash.error}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex items-start gap-4"><BookCover book={reservation.book} /><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Reservation #{reservation.id}</p><h1 className="mt-1 text-xl font-extrabold text-slate-900">{reservation.book.title}</h1><p className="mt-1 text-sm text-slate-500">{reservation.book.authors.length ? `by ${reservation.book.authors.join(', ')}` : 'Unknown author'}</p></div></div><Timeline reservation={reservation} /><dl className="grid gap-5 sm:grid-cols-2"><Detail label="Requested by" value={reservation.requester} /><Detail label="Preferred pickup" value={reservation.pickupDate} />{reservation.remarks && <div className="sm:col-span-2"><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Your notes</dt><dd className="mt-1 rounded-xl border border-slate-100 bg-slate-50 p-3 text-sm italic text-slate-700">“{reservation.remarks}”</dd></div>}</dl>{reservation.canCancel && <div className="mt-7 flex flex-col gap-4 border-t border-slate-100 pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">Changed your mind? You can cancel this reservation.</p><button type="button" onClick={cancel} disabled={cancelling} className="rounded-xl border border-red-200 px-5 py-2.5 text-sm font-bold text-red-600 hover:bg-red-50 disabled:opacity-50">{cancelling ? 'Cancelling…' : 'Cancel reservation'}</button></div>}</section></div></StudentLayout>;
}

function Timeline({ reservation }) { const negative = ['cancelled', 'rejected', 'expired'].includes(reservation.statusKey); const label = reservation.statusKey === 'pending' ? 'Awaiting approval' : reservation.status; return <section className="my-7 rounded-xl border border-slate-100 bg-slate-50 p-5"><h2 className="text-xs font-extrabold uppercase tracking-wider text-slate-700">Reservation timeline</h2><div className="mt-5 space-y-5"><Step complete title="Requested" date={reservation.requestDateLong} /><Step complete={reservation.statusKey !== 'pending'} negative={negative} title={label} date={reservation.statusDate} /></div>{reservation.statusKey === 'ready for pickup' && <div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><strong>Good news!</strong> Your book is ready at the library front desk.</div>}</section>; }
function Step({ complete, negative, title, date }) { return <div className="flex items-start gap-3"><span className={`mt-0.5 grid h-6 w-6 place-items-center rounded-full text-xs font-black text-white ${negative ? 'bg-red-500' : complete ? 'bg-[#102b70]' : 'bg-slate-300'}`}>{negative ? '×' : complete ? '✓' : '•'}</span><div><p className="text-sm font-extrabold text-slate-800">{title}</p>{date && <p className="mt-0.5 text-xs text-slate-500">{date}</p>}</div></div>; }
function Detail({ label, value }) { return <div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm font-bold text-slate-800">{value || '—'}</dd></div>; }
